### ISSUE TITLE
How to use with Win 10 Universal App

### ISSUE THREAD

**Issue by DavidShoe** [teichgraf/WriteableBitmapEx#13]
Using VS 2015 I have created a C# Win 10 Windows Universal App
I installed the nugget package V 1.5.0
I copied the sample code from the main page and am getting some errors:

                writeableBmp = BitmapFactory.New(1, 1).FromResource("Data/flower2.png");
FromResource does not exist

                int[] pixels = writeableBmp.Pixels;
Pixels does not exist

                WriteableBitmapExtensions.DrawLine(pixels, w, h, 1, 2, 30, 40, myIntColor);
DrawLine does not have a version which takes an int array

                writeableBmp.DrawCurve(pts, 0.5, Colors.Yellow);
Had to cast 0.5 to (float)0.5 as compiler can't convert double to float automatically

**Comment by teichgraf** [comment]
This is not an issue. It works different with WinRT/UWP.
Please see the sample code to get started. Open the Solution\WriteableBitmapEx_All.sln and check the WinRT folders for samples in that space.

**Comment by wstaelens** [comment]
Damn, can't see directly how it is done. You need to install Windows Phone 8.1 SDK first. 😢
