### ISSUE TITLE
How to create from array

### ISSUE THREAD

**Issue by vbisbest** [teichgraf/WriteableBitmapEx#14]
I have been banging my head on how to create a WriteableBitmap from a byte array.  One part that is killing me is that I do not know how big the Bitmap is but that is a required constructor.  So I have to create a bitmap just to get the higth and width.  Then when I use FromByteArray, it just seems botched.  It goes from 800k to 8000k with zero's filling in the array past 800.   Utilmatly I am trying to crop an image.   Any help would be much appreciated.  Thanks!

`                // Need to get original height and width
                BitmapImage bitmap = new BitmapImage();
                Task<InMemoryRandomAccessStream> task = Task.Run(() => GetRandomStream(imageData));
                task.Wait(10000);

                InMemoryRandomAccessStream ms = task.Result;          
                bitmap.SetSource(ms);

                // Create the WriteableBitmap
                WriteableBitmap wb = new WriteableBitmap(bitmap.PixelHeight, bitmap.PixelWidth);
                WriteableBitmap populatedImage = wb.FromByteArray(imageData);                
                WriteableBitmap cropped = populatedImage.Crop(crop_x, crop_y, width, height);

                return cropped.ToByteArray();`

**Comment by teichgraf** [comment]
Not sure about your code snippet as lots is missing. I'd recommend cloning the source code of WBX and then taking a look at the WriteableBitmapExBlitSample.WinRT sample.
