### ISSUE TITLE
FillEllipseCentered Alpha Channel isn't displayed properly

### ISSUE THREAD

**Issue by Normis** [teichgraf/WriteableBitmapEx#16]
`var fixationColor = Color.FromArgb(160, 255, 255, 255);`
`bitmap.FillEllipseCentered(point.X, point.Y, radius, radius, fixationColor.ToInt, true);`
`bitmap.DrawEllipseCentered(point.X, point.Y, radius, radius, _customBlack);`

this is the result (the background was white):
![20160615193939999](https://cloud.githubusercontent.com/assets/5094418/16094820/f934e896-330f-11e6-8f6f-38db21eee807.png)

**Comment by teichgraf** [comment]
Not sure what your ToInt method performs and which platform you test runs. 
You should use the method ConvertColor which converts from a Color to the right int value using pARGB (pre-mulitplied RGB which is what the WB uses).

```
var fixationColor = Color.FromArgb(160, 255, 255, 255);
int fixationColorInt = WriteableBitmapExtensions.ConvertColor(fixationColor);
bitmap.FillEllipseCentered(point.X, point.Y, radius, radius, fixationColorInt, true);
bitmap.DrawEllipseCentered(point.X, point.Y, radius, radius, _customBlack);
```

**Comment by Normis** [comment]
I also tried with ConvertColor before:
`var fixationColor = WriteableBitmapExtensions.ConvertColor(0.5, Colors.Red);`
`bitmap.FillEllipseCentered(point.X, point.Y, radius, radius, fixationColor, true);`
`bitmap.DrawEllipseCentered(point.X, point.Y, radius, radius, _customBlack);`
This is the result on a green and blue background:
![20160616150406173](https://cloud.githubusercontent.com/assets/5094418/16121828/c843b85e-33b2-11e6-97f8-3c07309cadbb.png)

**Comment by teichgraf** [comment]
What platform is that? WPF, WinRT, ...?
Do you have a repro project?

**Comment by Normis** [comment]
WPF and sorry but I don't have a repo.

**Comment by Normis** [comment]
[EllipseAlphaTest.zip](https://github.com/teichgraf/WriteableBitmapEx/files/319057/EllipseAlphaTest.zip)

**Comment by teichgraf** [comment]
A partial fix is implemented with c2e44253e96b4b425849eecb103afcd9d98dd841
But certain parts of the circle are still drawn multiple times so it doesn't look like expected. A fix might take longer as the algorithm is quite complex.

**Comment by Normis** [comment]
FYI at the moment I am using FillPolygon as a workaround.

**Comment by Normis** [comment]
My work around for anyone with this problem:

      public static void FillCircleCenteredHacked(this WriteableBitmap bitmap, int xc, int yc, int r, int color,
            bool doAlphaBlend = false)
        {
            bitmap.FillPolygon(GenerateCircle(r*10, xc, yc, r), color, true);
        }

        private static int[] GenerateCircle(int numberOfPoints, int xc, int yc, int radius)
        {
            var points = new int[numberOfPoints * 2];

            var angleIncrement = 2 * Math.PI / numberOfPoints;
            for (var idx = 0; idx < numberOfPoints - 1; idx++)
            {
                var angle = angleIncrement * idx;
                points[2 * idx] = Convert.ToInt32(xc + radius * Math.Cos(angle));
                points[2 * idx + 1] = Convert.ToInt32(yc + radius * Math.Sin(angle));
            }

            var lastPointOffset = 2 * (numberOfPoints - 1);
            points[lastPointOffset] = points[0];
            points[lastPointOffset + 1] = points[1];

            return points;
        }

**Comment by teichgraf** [comment]
Thank you!
