### ISSUE TITLE
Draw* methods lack a stroke thickness parameter

### ISSUE THREAD

**Issue by SuperJMN** [teichgraf/WriteableBitmapEx#19]
So it's not possible to draw, for example, a rectangle with a border whose thickness is more than 1 pixel

**Comment by teichgraf** [comment]
This is not an issue but a question. ;) 
You could simply draw multiple rectangles.

**Comment by mxmissile** [comment]
here is a quick extension method that handles thickness for `DrawRectangle`, could easily be adapted to the other Draw* methods.

```
public static class WritableBitmapExtensions
    {
        public static void DrawRectangle(this WriteableBitmap bmp, int x1, int y1, int x2, int y2, Color color, int thickness)
        {
            for (var i = 0; i < thickness; i++)
            {
                bmp.DrawRectangle(x1+i, y1+i, x2-i, y2-i, color);
            }
        }
    }
```
