### ISSUE TITLE
Unexpected behavior with ·FillEllipseCentered·

### ISSUE THREAD

**Issue by Blueve** [teichgraf/WriteableBitmapEx#2]
I found the `FillEllipseCentered` draw a extra line when drawing off the bitmap bounds.

There is my test code:
```csharp
bitmap.FillEllipseCentered(100, -100, 10, 10, Colors.Red);
bitmap.FillEllipseCentered(-100, 100, 10, 10, Colors.Green);
bitmap.FillEllipseCentered(700, 100, 10, 10, Colors.Blue);
bitmap.FillEllipseCentered(100, 700, 10, 10, Colors.Purple);
```
Actually result:
![](http://blueve.me/wp-content/uploads/2015/10/result.gif)

Expected result should be a empty bitmap.

This problem occurs on the left\bottom\top edge.

> My Version: 1.5.0.0

**Comment by teichgraf** [comment]
Fixed with e05f95353bf08dfbd4578c094ad164d14ac86907
