### ISSUE TITLE
UWP - an easy way to add, edit and move basic shapes?

### ISSUE THREAD

**Issue by Goldstrike** [teichgraf/WriteableBitmapEx#21]
Sorry for my question as it's not an issue...
But I'm looking for an easy way that allowing a user to add basic shapes (rectangle, ellipse, ...) on a WriteabkeBitmapEx that contains a photo.
Then the shape must be moved on the area, resizable and customizable (foreground color).
I have looked to samples but I didn't found a similar case...

**Comment by BrannonKing** [comment]
For your usage, where mouse interaction is required, you should use the Shape controls available in UWP. Get a book on it or WPF. It sounds like you need a general overview of the framework.

**Comment by teichgraf** [comment]
Take a look at the WriteableBitmapExCurveSample. Disable the "Growing Plant Demo"and then you can see it has interactions built-in to move rectangle which you can adapt for your case.
