### ISSUE TITLE
Requires pbgra32 but check removed

### ISSUE THREAD

**Issue by Scantheus** [teichgraf/WriteableBitmapEx#24]
Was trying to Flip an RGB24 in a WPF app and got an access violation. Tracked it down to BitmapContext. It calculates _length using a width as BackBufferStride / SizeOfArgb. SizeOfArgb is a constant of 4. 

Above the calculation for length is a commented out check for Pbgra32 that would throw an exception.

#if WPF
         //// Check if it's the Pbgra32 pixel format
         //if (writeableBitmap.Format != PixelFormats.Pbgra32)
         //{
         //   throw new ArgumentException("The input WriteableBitmap needs to have the Pbgra32 pixel format. Use the BitmapFactory.ConvertToPbgra32Format method to automatically convert any input BitmapSource to the right format accepted by this class.", "writeableBitmap");
         //}

            double width = _writeableBitmap.BackBufferStride / WriteableBitmapExtensions.SizeOfArgb;
            _length = (int)(width * _pixelHeight);

**Comment by teichgraf** [comment]
There was a reason why it was disabled but can't recall now. :)
https://writeablebitmapex.codeplex.com/SourceControl/changeset/111026 
The better way would be to not have a static SizeOfArgb = 4 but rather use it dynamic for WPF.
