### ISSUE TITLE
WPF .Clear( full transparent magenta ) fills with full transparent black instead

### ISSUE THREAD

**Issue by Riva3000** [teichgraf/WriteableBitmapEx#25]
With WPF flavour of WriteableBitmapEx
if I do
`wBitmap.Clear( Color.FromArgb(0x0, 0xFF, 0x0, 0xFF) );`
on fresh created, empty, BGRA32 WritableBitmap,
I will end up with bitmap filled with 100% transparent black instead of magenta.

**Comment by teichgraf** [comment]
It's using pre-multiplied alpha, so 0 * FF = 0.
