### ISSUE TITLE
writeablebitmapex FillEllipseCentered with center out of boundary

### ISSUE THREAD

**Issue by saravanadeva92** [teichgraf/WriteableBitmapEx#26]
I have writeablebitmap with width and height equal to 580, i need to draw a circle in it. So i will use bmp.FillEllipseCentered(290,290,290,290,color);

I need to zoom this circle by scaling factor 2, say the radius will be 290 *2 = 580, so that i will move the scroll bar and i will be able to see the curves of the circle by changing the center position. bmp.FillEllipseCentered(580-x,580-y,580,580,color);

When i zooming again i.e (bmp.FillEllipseCentered(1160-x,1160-y,1160,1160,color);), circle is not coming i was getting some lines at the end region. Is there any way to achieve this fill circle when it is outside of boundary.

**Comment by teichgraf** [comment]
It's being clipped if the provided coordinates are outside the bitmap, so this expected behavior. Make sure to draw within the bounds.
