### ISSUE TITLE
latest nuget package is outdated

### ISSUE THREAD

**Issue by nagblock** [teichgraf/WriteableBitmapEx#27]
It's awesome that WriteableBitmapEx is offered as a Nuget package. The latest version published on http://nuget.org/List/Packages/WriteableBitmapEx however is from March 2015.

It's possible to build and publish nuget packages automatically these days. Perhaps with the move to Github you'd want to explore than option?

**Comment by teichgraf** [comment]
Latest version is 1.5.1  which is 5 months old now. 
The library is quite stable thee days so there are not a lot of changes.
