### ISSUE TITLE
UWP project is not available.

### ISSUE THREAD

**Issue by mb12** [teichgraf/WriteableBitmapEx#33]
Is there a UWP project available for WriteableBitmapEx? 
None of the projects available under Source is a UWP project.

https://github.com/teichgraf/WriteableBitmapEx/tree/master/Source

**Comment by wstaelens** [comment]
see https://github.com/teichgraf/WriteableBitmapEx/issues/13 👎

**Comment by teichgraf** [comment]
These days with UWP you should look into Win2D and use a much faster and more efficient API.
