### ISSUE TITLE
Create Polygon with color of border is different from inside

### ISSUE THREAD

**Issue by nguyenquangdien** [teichgraf/WriteableBitmapEx#34]
I would like to draw a polygon that border's color is not same as inside's color as below:
![untitled](https://user-images.githubusercontent.com/26354463/29245435-afaad2ca-8003-11e7-9a4c-c0cd71bfd178.png)

I think this it can be achieved by combining FillPolygon and DrawPolygon (create border).
However, DrawPolygon is not available in WriteableBitmapEx.

I tried to use DrawPolyline, but the result is not good, the polygon created by FillPolygon and DrawPolyline are not same.

Do you have any suggestion for me?
Thank you very much!

**Comment by teichgraf** [comment]
You could use two Polygons. Draw the black one a bit larger and after that the blue one. Not very efficient but works. 
Also you could draw the border lines manually around.
