### ISSUE TITLE
SetPixel / SetPixeli is too slow

### ISSUE THREAD

**Issue by ShannonZ** [teichgraf/WriteableBitmapEx#38]
I have a 3-d int array like: 
int[ , , ] = new int[512,512,128];
which  containing 128 images each has 512*512 pixels.
I used SetPixel(i) in a for-loop but the speed is too slow.
Is there any faster way to implement this?

**Comment by teichgraf** [comment]
There sure is but it's not an Issue so this will be closed. 

Don't use the SetPixel method for mass pixel manipulation. Implement it on your own. See the BitmapConext.CopyPixels method on how to access the pixels in the right order, then look at the SetPixel method.

If you want to use the SetPixel or any other WriteableBitmapEx method, then do it that way inside a BitmapContext scope to avoid an unnecessary overhead:

```
using (bitmap.GetBitmapContext())
{
	Color c = Colors.Red;
	for (int x = 0; x < bitmap.PixelWidth; x++)
	{
		for (int y = 0; y < bitmap.PixelHeight; y++)
		{
			bitmap.SetPixel(x, y, c);
		}
	}
}
```

**Comment by ShannonZ** [comment]
Thank you very much.
Is there any chatting room in gitter.im? Where can I ask questions?

**Comment by ShannonZ** [comment]
I used the GetBitmapContext() and now it's 4x faster. While the loading is still time-consuming. Any faster way to do this?@teichgraf
