### ISSUE TITLE
BlitRender does not support blending

### ISSUE THREAD

**Issue by Artfunkel** [teichgraf/WriteableBitmapEx#39]
I want to draw a translucent decal onto an existing image with a transformation. When I call `BlitRender` the library replaces _all_ colour values in the destination image with the decal's, resulting in a square hole.

I'm having to fall back on GDI rendering to work around this.

**Comment by teichgraf** [comment]
Please note depending on your target platform, WriteableBitmap uses pre-multiplied RGB, so you might have to change the color to use. 
Can you provide a repro sample I can take a look at?

**Comment by Artfunkel** [comment]
I don't have any code left, sorry. I ditched this library when I realised that I was supposed to be using DrawingVisual.
