### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by HagenFelix** [teichgraf/WriteableBitmapEx#42]
Good catch. Should be fixed with next release.

_Originally posted by @teichgraf in https://github.com/teichgraf/WriteableBitmapEx/issues/29#issuecomment-336494045_

Unfortunately, DLL version is still 1.5.2 ... :-(

**Comment by teichgraf** [comment]
You mean the WPF DLLs I assume in the latest NuGET package? 

I pushed a package with 1.6.1 to NuGet also containing .NET Core 3.0 Preview (and still .NET FW 4) and UWP Win10.

I'm about to push a new build later today.

**Comment by teichgraf** [comment]
Version 1.6.2 should be available via NuGet in a few hours. 
https://www.nuget.org/packages/WriteableBitmapEx/1.6.2

The WPF and UWP DLLs also use the 1.6.2 version number. 
The Silverlight and Windows Phone DLLs are older and won't be maintained any longer but are still part of the package for now.

Thanks for reporting the issue.

**Comment by HagenFelix** [comment]
Yes, it's about WriteableBitmapEx.Wpf.dll

Fresh build, but version number (file as well as product) still 1.5.2.0

**Comment by teichgraf** [comment]
The indexing just finished but it might take a bit longer until 1.6.2 is listed in the Package Manger.

You can already download and verify from the NuGet page:
https://www.nuget.org/packages/WriteableBitmapEx/1.6.2

**Comment by teichgraf** [comment]
OK, just when I hit sent, it appeared in the Pack Man as well, so you can try in Visual Studio as well now.
