### ISSUE TITLE
FillRectangle does not fill according to its parameters

### ISSUE THREAD

**Issue by jeroenwalter** [teichgraf/WriteableBitmapEx#5]
Hi

Following case:
var bmp = BitmapFactory.New(25, 25);
bmp.FillRectangle(0, 0, 24, 24, Color.FromArgb(255, 255, 0, 0));

I expect this to have the same result as:
bmp.Clear(Color.FromArgb(255, 255, 0, 0));
Because the x1,y1,x2 and y2 parameters encompass the entire bitmap.

However, FillRectangle does not fill the pixels on the right and bottom side of the given rectangle.

Even this does not fill the entire bitmap.
bmp.FillRectangle(0, 0, 26, 26, Color.FromArgb(255, 255, 0, 0));
This is caused because the x2 and y2 parameters are clamped to the width and height of the bitmap.

In my opinion this is not correct.
Either the code must be fixed so the right and bottom sides are inclusive instead of exclusive, or the documentation of the function must be altered to describe this behaviour.

As it is now it is never possible to fill the right side or the bottom side of the bitmap.

**Comment by jeroenwalter** [comment]
I've seen this issue, http://writeablebitmapex.codeplex.com/workitem/21276

This is solved incorrectly.

As it is now it is never possible to fill the right side or the bottom side of the bitmap.

It would be better to change the parameters of FillRectangle from x1,y1,x2,y2 to x,y,width,height.

**Comment by teichgraf** [comment]
Good point.

**Comment by polipo** [comment]
Confirm the problem,
a bitmap with WIDTH = 10
if a call DrawRectangle (0,0,10,10) the rectangle not fill entire width of the bitmap!

  // Clamp boundaries
                if (x1 < 0) { x1 = 0; }
                if (y1 < 0) { y1 = 0; }
                if (x2 < 0) { x2 = 0; }
                if (y2 < 0) { y2 = 0; }
                if (x1 >= w) { x1 = w - 1; }
                if (y1 >= h) { y1 = h - 1; }
                if (x2 >= w) { x2 = w - 1; } //this will be if (x2 > w) { x2 = w - 1; } 
                if (y2 >= h) { y2 = h - 1; } //this will be  if (y2 > h) { y2 = h - 1; }

Please can you correct it ?

**Comment by teichgraf** [comment]
Would you mind putting it in a pull request?

**Comment by polipo** [comment]
done it

**Comment by teichgraf** [comment]
Thanks. I will take a look.
