### ISSUE TITLE
Is DrawLine x2 correct?

### ISSUE THREAD

**Issue by polipo** [teichgraf/WriteableBitmapEx#9]
Try to create a bitmap with (10px width , 10px height)
now draw a rectangle and a line with same dimension (< than wBitmap.lenght)
The result is a different lenght of the rectangle and line, why ?

Code example:
wBitmap = ...(10,10)
wBitmap.FillRectangle(0, 0, 5, 10, System.Windows.Media.Colors.Aquamarine);
wBitmap.DrawLine(0, 0, 5, 10, System.Windows.Media.Colors.Blue);

The blue line is one pixel longer than rectangle!

Instead  drawing a line and rectangle with full lenght of the bitmap (10px) is correct.

Code example:
wBitmap.FillRectangle(0, 0, 10, 10, System.Windows.Media.Colors.Aquamarine);
wBitmap.DrawLine(0, 0, 10, 10, System.Windows.Media.Colors.Blue);

There's a bug

**Comment by teichgraf** [comment]
Should be fixed by now.
